# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Communication/AmongUsAI/NNOutput.proto, Recording/DeadBodies/DeadBodiesFrame.proto, Recording/DeadBodies/DeadBodyData.proto, Recording/Frame.proto, Recording/LocalPlayer/LocalPlayerFrame.proto, Recording/Map/DoorData.proto, Recording/Map/MapFrame.proto, Recording/Map/VentData.proto, Recording/OtherPlayers/OtherPlayerData.proto, Recording/OtherPlayers/OtherPlayersFrame.proto, Recording/PositionData.proto, Utilities/MyVector2.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass(eq=False, repr=False)
class MyVector2(betterproto.Message):
    x: float = betterproto.float_field(1)
    y: float = betterproto.float_field(2)


@dataclass(eq=False, repr=False)
class NnOutput(betterproto.Message):
    desired_move_direction: "MyVector2" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class DeadBodyData(betterproto.Message):
    parent_id: int = betterproto.uint32_field(1)
    position: "MyVector2" = betterproto.message_field(2)
    first_seen_time: float = betterproto.float_field(3)
    nearby_players: bytes = betterproto.bytes_field(4)


@dataclass(eq=False, repr=False)
class DeadBodiesFrame(betterproto.Message):
    dead_bodies: List["DeadBodyData"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class LocalPlayerFrame(betterproto.Message):
    did_report: bool = betterproto.bool_field(1)
    did_vent: bool = betterproto.bool_field(2)
    did_kill: bool = betterproto.bool_field(3)
    sabotage_used: int = betterproto.uint32_field(4)
    doors_used: int = betterproto.uint32_field(5)
    raycast_obstacle_distances: List[float] = betterproto.float_field(6)


@dataclass(eq=False, repr=False)
class PositionData(betterproto.Message):
    total_distance: float = betterproto.float_field(1)
    next_node_position: "MyVector2" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class DoorData(betterproto.Message):
    position: "PositionData" = betterproto.message_field(1)
    is_open: bool = betterproto.bool_field(2)


@dataclass(eq=False, repr=False)
class VentData(betterproto.Message):
    id: int = betterproto.int32_field(1)
    position: "PositionData" = betterproto.message_field(2)
    connecting_vents: List["ConnectingVentData"] = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class ConnectingVentData(betterproto.Message):
    id: int = betterproto.int32_field(1)
    position: "MyVector2" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class MapFrame(betterproto.Message):
    nearby_doors: List["DoorData"] = betterproto.message_field(1)
    nearby_vents: List["VentData"] = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class OtherPlayerData(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    last_seen_position: "MyVector2" = betterproto.message_field(2)
    last_seen_time: float = betterproto.float_field(3)
    times_saw_vent: int = betterproto.uint32_field(4)
    round_time_visible: float = betterproto.float_field(5)
    game_time_visible: float = betterproto.float_field(6)


@dataclass(eq=False, repr=False)
class OtherPlayersFrame(betterproto.Message):
    last_seen_players: List["OtherPlayerData"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class Frame(betterproto.Message):
    dead_bodies: "DeadBodiesFrame" = betterproto.message_field(1)
    local_player: "LocalPlayerFrame" = betterproto.message_field(2)
    map: "MapFrame" = betterproto.message_field(3)
    other_players: "OtherPlayersFrame" = betterproto.message_field(4)
